# Site settings
title: Hey, Cascadia!
email: mike@heycascadia.com
description: "Rite an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://www.heycascadia.com"
twitter_username: 
github_username:  MikeJeffrey

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "default"
